import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import type { RiskSummary } from "../risk/summarize.js";
import type { ChecklistItem } from "../checks/checklist.js";

const RISK_EMOJI = {
  low: "🟢",
  medium: "🟡",
  high: "🔴",
} as const;

export function generateMarkdown(
  summary: RiskSummary,
  checklistItems: ChecklistItem[]
): string {
  const emoji = RISK_EMOJI[summary.risk.level];
  const lines: string[] = [];

  // Header
  lines.push("# Release Guard Report");
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(`| Item | Value |`);
  lines.push(`|------|-------|`);
  lines.push(`| Branch | \`${summary.branch}\` |`);
  lines.push(`| Base | \`${summary.baseBranch}\` |`);
  lines.push(`| Time | ${summary.timestamp} |`);
  lines.push(`| Files Changed | ${summary.changedFiles.length} |`);
  lines.push(
    `| Total Changes | +${totalInsertions(summary)} -${totalDeletions(summary)} |`
  );
  lines.push(`| Risk Level | ${emoji} **${summary.risk.level.toUpperCase()}** |`);
  lines.push("");

  // Changed Files
  lines.push("## Changed Files");
  lines.push("");
  if (summary.changedFiles.length === 0) {
    lines.push("No files changed.");
  } else {
    lines.push("| File | Changes |");
    lines.push("|------|---------|");
    for (const file of summary.changedFiles) {
      const changes = file.binary
        ? "binary"
        : `+${file.insertions} -${file.deletions}`;
      lines.push(`| \`${file.path}\` | ${changes} |`);
    }
  }
  lines.push("");

  // Check Results
  lines.push("## Check Results");
  lines.push("");
  if (summary.checkResults.length === 0) {
    lines.push("No checks configured.");
  } else {
    lines.push("| Check | Status | Duration |");
    lines.push("|-------|--------|----------|");
    for (const check of summary.checkResults) {
      const status = check.passed ? "✓ Passed" : "✗ Failed";
      const duration = formatDuration(check.durationMs);
      lines.push(`| ${check.name} | ${status} | ${duration} |`);
    }

    // Show failed check output
    const failed = summary.checkResults.filter((c) => !c.passed);
    if (failed.length > 0) {
      lines.push("");
      lines.push("### Failed Check Details");
      for (const check of failed) {
        lines.push("");
        lines.push(`**${check.name}** (\`${check.command}\`):`);
        lines.push("```");
        lines.push(check.output.slice(0, 2000) || "(no output)");
        lines.push("```");
      }
    }
  }
  lines.push("");

  // Risk Analysis
  lines.push("## Risk Analysis");
  lines.push("");
  lines.push(`**Risk Level: ${emoji} ${summary.risk.level.toUpperCase()}**`);
  lines.push("");
  if (summary.risk.reasons.length > 0) {
    lines.push("Reasons:");
    for (const reason of summary.risk.reasons) {
      lines.push(`- ${reason}`);
    }
  }
  lines.push("");

  // Checklist
  if (checklistItems.length > 0) {
    lines.push("## Checklist");
    lines.push("");
    for (const item of checklistItems) {
      const marker = item.triggered ? "⚠️" : "  ";
      lines.push(`- ${marker} ${item.text}`);
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("*Generated by Release Guard Lite*");
  lines.push("");

  return lines.join("\n");
}

export interface CheckResultWithCommand {
  name: string;
  command: string;
  passed: boolean;
  output: string;
  durationMs: number;
}

export function writeReport(
  markdown: string,
  cwd?: string
): string {
  const dir = cwd ?? process.cwd();
  const reportDir = resolve(dir, ".release-guard");
  const reportPath = resolve(reportDir, "latest-report.md");

  mkdirSync(reportDir, { recursive: true });
  writeFileSync(reportPath, markdown, "utf-8");

  return reportPath;
}

function totalInsertions(summary: RiskSummary): number {
  return summary.changedFiles.reduce((sum, f) => sum + f.insertions, 0);
}

function totalDeletions(summary: RiskSummary): number {
  return summary.changedFiles.reduce((sum, f) => sum + f.deletions, 0);
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}
